#! /bin/bash
# Audio Splicer

if [ $# -lt 3 ]; then
echo "$0: Input, Delen, Extensie"
exit
fi

INPUT=$1
DELEN=$2
EXT=$3
INPUTPAD=`dirname "$INPUT"`
SAMPLES=$(soxi -s "${INPUT}")
let SAMPLESPERDEEL=${SAMPLES}/${DELEN}
BEGIN=0
i=0

while [ ${i} -lt ${DELEN}  ]
do
echo "Processing " loop${i}
sox "${INPUT}" "${INPUTPAD}/loop${i}${EXT}" trim ${BEGIN}s ${SAMPLESPERDEEL}s
let i=${i}+1
let BEGIN=${BEGIN}+${SAMPLESPERDEEL}
done

echo "DONE"

