/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "Gui.h"

//==============================================================================
/**
*/
class Mpeq1AudioProcessorEditor  : public AudioProcessorEditor
{
public:
    Gui custom;
    Mpeq1AudioProcessorEditor (Mpeq1AudioProcessor&);
    ~Mpeq1AudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    Mpeq1AudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (Mpeq1AudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
